---
name: CI checks

on: push

jobs:
  cargo-nursery:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-nursery.yml@main
    with:
      toolchain: stable

  cargo-publish:
    needs:
      - cargo-nursery
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish.yml@main
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    with:
      toolchain: stable
    secrets: inherit

  cleanup:
    needs:
      - cargo-publish
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    secrets: inherit
